// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: accountservice.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreatedAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatedAccountRequest) Reset() {
	*x = CreatedAccountRequest{}
	mi := &file_accountservice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatedAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatedAccountRequest) ProtoMessage() {}

func (x *CreatedAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_accountservice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatedAccountRequest.ProtoReflect.Descriptor instead.
func (*CreatedAccountRequest) Descriptor() ([]byte, []int) {
	return file_accountservice_proto_rawDescGZIP(), []int{0}
}

func (x *CreatedAccountRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreatedAccountRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type CreatedAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=accountId,proto3" json:"accountId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatedAccountResponse) Reset() {
	*x = CreatedAccountResponse{}
	mi := &file_accountservice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatedAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatedAccountResponse) ProtoMessage() {}

func (x *CreatedAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_accountservice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatedAccountResponse.ProtoReflect.Descriptor instead.
func (*CreatedAccountResponse) Descriptor() ([]byte, []int) {
	return file_accountservice_proto_rawDescGZIP(), []int{1}
}

func (x *CreatedAccountResponse) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type DeletedAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountID     string                 `protobuf:"bytes,1,opt,name=accountID,proto3" json:"accountID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletedAccountRequest) Reset() {
	*x = DeletedAccountRequest{}
	mi := &file_accountservice_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletedAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletedAccountRequest) ProtoMessage() {}

func (x *DeletedAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_accountservice_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletedAccountRequest.ProtoReflect.Descriptor instead.
func (*DeletedAccountRequest) Descriptor() ([]byte, []int) {
	return file_accountservice_proto_rawDescGZIP(), []int{2}
}

func (x *DeletedAccountRequest) GetAccountID() string {
	if x != nil {
		return x.AccountID
	}
	return ""
}

var File_accountservice_proto protoreflect.FileDescriptor

const file_accountservice_proto_rawDesc = "" +
	"\n" +
	"\x14accountservice.proto\x1a\x1bgoogle/protobuf/empty.proto\"E\n" +
	"\x15CreatedAccountRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"6\n" +
	"\x16CreatedAccountResponse\x12\x1c\n" +
	"\taccountId\x18\x01 \x01(\tR\taccountId\"5\n" +
	"\x15DeletedAccountRequest\x12\x1c\n" +
	"\taccountID\x18\x01 \x01(\tR\taccountID2\x97\x01\n" +
	"\x0eAccountService\x12B\n" +
	"\rCreateAccount\x12\x16.CreatedAccountRequest\x1a\x17.CreatedAccountResponse\"\x00\x12A\n" +
	"\rDeleteAccount\x12\x16.DeletedAccountRequest\x1a\x16.google.protobuf.Empty\"\x00B\aZ\x05./;pbb\x06proto3"

var (
	file_accountservice_proto_rawDescOnce sync.Once
	file_accountservice_proto_rawDescData []byte
)

func file_accountservice_proto_rawDescGZIP() []byte {
	file_accountservice_proto_rawDescOnce.Do(func() {
		file_accountservice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_accountservice_proto_rawDesc), len(file_accountservice_proto_rawDesc)))
	})
	return file_accountservice_proto_rawDescData
}

var file_accountservice_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_accountservice_proto_goTypes = []any{
	(*CreatedAccountRequest)(nil),  // 0: CreatedAccountRequest
	(*CreatedAccountResponse)(nil), // 1: CreatedAccountResponse
	(*DeletedAccountRequest)(nil),  // 2: DeletedAccountRequest
	(*emptypb.Empty)(nil),          // 3: google.protobuf.Empty
}
var file_accountservice_proto_depIdxs = []int32{
	0, // 0: AccountService.CreateAccount:input_type -> CreatedAccountRequest
	2, // 1: AccountService.DeleteAccount:input_type -> DeletedAccountRequest
	1, // 2: AccountService.CreateAccount:output_type -> CreatedAccountResponse
	3, // 3: AccountService.DeleteAccount:output_type -> google.protobuf.Empty
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_accountservice_proto_init() }
func file_accountservice_proto_init() {
	if File_accountservice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_accountservice_proto_rawDesc), len(file_accountservice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_accountservice_proto_goTypes,
		DependencyIndexes: file_accountservice_proto_depIdxs,
		MessageInfos:      file_accountservice_proto_msgTypes,
	}.Build()
	File_accountservice_proto = out.File
	file_accountservice_proto_goTypes = nil
	file_accountservice_proto_depIdxs = nil
}
