apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zookeeper-single-pvc-data
  namespace: zookeeper-single
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi # Adjust storage size as needed
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zookeeper-single-pvc-logs
  namespace: zookeeper-single
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi # Adjust storage size as needed